server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Heebum/microservicios.git
          clone-on-start: true
#          uri: git@github.com:Heebum/microservicios.git
          searchPath: config-data
          username: ${GIT_USER}
          password: ${GIT_PASS}
          default-label: data
          timeout: 4

#  security:
#    user:
#      name: root
#      password: s3cr3t

  application:
    name: config-server

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

