server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Heebum/microservicios.git
#          uri: git@github.com:Heebum/microservicios.git
          skipSslValidation: true
          searchPath: config-data
          username: ${GIT_USER}
          PASSWORD: ${GIT_PASS}
          default-label: data
          timeout: 4

      failFast: true

  security:
    user:
      name: root
      password: s3cr3t
  application:
    name: config-server

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

